/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_img (XDR *xdrs, img *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->img_val, (u_int *) &objp->img_len, ~0))
		 return FALSE;
	return TRUE;
}
