/*
 * The file will be generated by rpcgen
 *//*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int img_len;
	char *img_val;
} img;

#define img_prog 0x20000002
#define img_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define minify_img 1
extern  img * minify_img_1(img , CLIENT *);
extern  img * minify_img_1_svc(img , struct svc_req *);
extern int img_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define minify_img 1
extern  img * minify_img_1();
extern  img * minify_img_1_svc();
extern int img_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_img (XDR *, img*);

#else /* K&R C */
extern bool_t xdr_img ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
